/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v3/reports/{templateId}/exportSome": {
    /** Exports a selection of report answers and associated images given its id as either fwbundle or zipped csv. The "fields" array in the body determines the columns in any csv export. Include "responses" if questions and answers are required. */
    post: operations["post-v3-reports-templateId-exportOne-answerId"];
    parameters: {
      path: {
        templateId: string;
      };
    };
  };
  "/v3/areas/exportOne/{areaId}": {
    /** Exports an and associated images given its id as either fwbundle or zipped csv, shp or geojson. The "fields" array in the body determines the columns in any csv export. */
    post: operations["post-v3-areas-exportOne-areaId"];
    parameters: {
      path: {
        areaId: string;
      };
    };
  };
  "/v3/reports/{templateId}/exportAll": {
    /** Exports all report answers and associated images available to the user for the given template as either fwbundle or zipped csv.The "fields" array in the body determines the columns in any csv export. Include "responses" if questions and answers are required. */
    post: operations["post-v3-reports-templateId-exportAll"];
    parameters: {
      path: {
        templateId: string;
      };
    };
  };
  "/v3/areas/exportAll": {
    /** Exports all areas and associated images available to the user as either fwbundle or zipped csv, shp or geojson. The "fields" array in the body determines the columns in any csv export. */
    post: operations["post-v3-areas-exportAll"];
    parameters: {};
  };
}

export interface components {
  schemas: {};
  responses: {
    /** Error Response */
    Error: {
      content: {
        "application/json": {
          errors: {
            status: number;
            detail: string;
          }[];
        };
      };
    };
    /** Healthcheck response */
    Healthcheck: {
      content: {
        "application/json": {
          uptime?: number;
        };
      };
    };
  };
  requestBodies: {
    "Export-areas-request": {
      content: {
        "application/json": {
          fileType?: string;
          fields?: string[];
        };
      };
    };
  };
}

export interface operations {
  /** Exports a selection of report answers and associated images given its id as either fwbundle or zipped csv. The "fields" array in the body determines the columns in any csv export. Include "responses" if questions and answers are required. */
  "post-v3-reports-templateId-exportOne-answerId": {
    parameters: {
      path: {
        templateId: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            data?: string;
          };
        };
      };
      401: components["responses"]["Error"];
      404: components["responses"]["Error"];
    };
    requestBody: {
      content: {
        "application/json": {
          ids?: {
            templateid?: string;
            reportid?: string;
          }[];
          language?: string;
          fileType?: string;
          fields?: string[];
        };
      };
    };
  };
  /** Exports an and associated images given its id as either fwbundle or zipped csv, shp or geojson. The "fields" array in the body determines the columns in any csv export. */
  "post-v3-areas-exportOne-areaId": {
    parameters: {
      path: {
        areaId: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            data?: string;
          };
        };
      };
      401: components["responses"]["Error"];
      404: components["responses"]["Error"];
    };
    requestBody: components["requestBodies"]["Export-areas-request"];
  };
  /** Exports all report answers and associated images available to the user for the given template as either fwbundle or zipped csv.The "fields" array in the body determines the columns in any csv export. Include "responses" if questions and answers are required. */
  "post-v3-reports-templateId-exportAll": {
    parameters: {
      path: {
        templateId: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            data?: string;
          };
        };
      };
      401: components["responses"]["Error"];
      404: components["responses"]["Error"];
    };
    requestBody: {
      content: {
        "application/json": {
          language?: string;
          fileType?: string;
          fields?: string[];
        };
      };
    };
  };
  /** Exports all areas and associated images available to the user as either fwbundle or zipped csv, shp or geojson. The "fields" array in the body determines the columns in any csv export. */
  "post-v3-areas-exportAll": {
    parameters: {};
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            data?: string;
          };
        };
      };
      401: components["responses"]["Error"];
      404: components["responses"]["Error"];
    };
    requestBody: components["requestBodies"]["Export-areas-request"];
  };
}

export interface external {}
