name: Pull request utilities

on:
  - pull_request
  
jobs:
  labeler:
    name: Assign labels to PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - uses: actions/labeler@v5
      - uses: pascalgn/size-label-action@v0.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "0": "xs",
              "20": "s",
              "50": "m",
              "200": "l",
              "800": "xl"
            }

  semantic:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
